spring:
  application:
    name: add-employee-service
  resources:
    chain:
      enabled: true

server:
  port: 8303

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8302/eureka
    instance:
      hostname: localhost

dbservice:
  name: 'db-service'